# Site setings
name: 'Pactum Partners'
description: 'Inter-Family Office Synergistic Development'
meta_description: 'Pactum Partners'
greetings: 'Hello & Welcome to Pactum Partners'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://pactumpartners.com/
disqus: 'PACTUM'
mailchimp_url: 
cover_image: covers/6.jpeg
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: youremail@email.com
contact_page_description: "For inquires, please contact us below."
thankyou_page_description: "Thank you for your inquiry."

# Social links
twitter: 'username'
facebook: 'username'
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'username'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: The Pactum Partners Philosophy
    url: /pactum-partners-philosophy
 - text: Testimonials
    url: /testimonials
  - text: Contact Pactum
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
#   - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
