# Site setings
name: 'PACTUM PARTNERS'
description: 'Inter-Family Office Synergistic Development'
meta_description: 'Connecting Family Offices.'
greetings: 'Hello & Welcome to PACTUM PARTNERS'
logo:
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: www.pactumpartners.com
disqus: 'justgoodthemes'
mailchimp_url:
cover_image: covers/cover.png
# Add your GA Tracking Id
ga_analytics: 'UA-208025494-1'

# Contact form setings
email: m.calvoelhauge@pactumpartners.com
contact_page_description: "PACTUM PARTNERS - Inquiry Form"
thankyou_page_description: "Thank you for your inquiry!"

# Social links
twitter: 'username'
facebook: 'username'
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'username'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Philosophy
    url: /Pactum-Partners-Philosophy
  - text: Team
    url: /team
  - text: Partners
    url: /partners
  - text: Contact
    url: /contactus

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 7
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
